#-*-makefile-*-

TEX := theory \
       beamer_cfg commands ocaml_syntax \
       string_sys calculator booleans term_sys stacks sharing tail_calls \
       induction termination concat_assoc unification concat_length \
       ho_stack_folds inferece_rules binary_trees bt_traversals bst \
       analysis mini_ml

ORIENT := landscape
USE_PS := yes
