#-*-makefile-*-

TEX := theory \
       commands beamer_cfg ocaml_syntax \
       string_sys calculator booleans term_sys \
       stacks sharing tail_calls induction \
       termination proofs analysis mini_ml

ORIENT := landscape
USE_PS := yes
